name: Themes Admin
version: 1.10.1
description: Themes Admin plugin to manage site themes for the website frontend.
icon:
  name: paint-brush
  set: "fontawesome|solid"
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/themes-admin
bugs: https://github.com/flextype-plugins/themes-admin/issues
license: MIT

dependencies:
  flextype: 0.9.16
  twig: '>=2.0.0'
  admin: '>=1.0.0'
  form: '>=1.0.0'
  site: '>=1.0.0'
  acl: '>=1.0.0'
